language: node_js
node_js:
- '11'
deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/publish-generators-outputs.sh
  on:
    branch: master
env:
  global:
  - secure: OlcVmxhwWCQ8/IVAXcptrhdi7bywUu98FQ4yV/ABMNn0KTn372DQKLNo1wRxkz4YLdzKzHc3KEHeGW8mUKl8MZvwzKaoZTu93s+Q6nKOgjFiCw532pNsvkQnuaufkwtZqhPXQE1JMnHmPnWL3S3oDsnn8hgTKRmmmADkokfaWl6DldDpLzuf18fnoVIUklZPKa3XO8Slp4iDqfRDjinFfHfLbTznNqIQNPUCkcfV98o+cWKXhaTZH3L2OLQSe9C6Zo2l8kv6qs2TXVqbKFp4dEjuEXEE3FbYWvJtIv9fjnMwHxmXm336s1Il516xrjY+kYmZwY3wyWBaZtJJJpQY9UjbB4tNKjbz4EbR5nlg0voY7QS+DQtDjZiiZqoF9qMOuL9OLGQsyfEoiBcr9+DlgcAQrWC8vSpbyGlTgis4bDpG0dxFtovjJRZiZDK6+SsOaiCilw12nLifO6EvLowMxrWKw4YB6tk6eNMDAfXas35QbOyA1tQn6L/NnVy7VXmUWHJN66HGkFBixZERkusD4GOvDCfC39zoeDyYXgeqKGhjIYwiM4jWVG46d3vc81oV2T/5ySuLls7XWEEsb8OUB86sSY7AIlt1gE7hqisMIskp32ZILcB+g5W+yX6vXnds19TkmMqgJwnMdMIKv6uOf8RspfLTNFLy11hYXvzy1rw=
